import sys

def to_dms_string(deg, is_lat):
    d = int(deg)
    m_float = abs(deg - d) * 60
    m = int(m_float)
    s = (m_float - m) * 60
    direction = ''
    if is_lat:
        direction = 'N' if deg >= 0 else 'S'
    else:
        direction = 'E' if deg >= 0 else 'W'
    return f'{abs(d)}° {m}\' {s:.3f}" {direction}'

def generate_report():
    output_lines = sys.stdin.readlines()
    
    final_lat = None
    final_lon = None
    distances_used = []
    source_xy_local = None
    
    in_distances_section = False
    for line in output_lines:
        line = line.strip()
        if line.startswith("Final_Lat:"):
            final_lat = float(line.split(":")[1].strip())
        elif line.startswith("Final_Lon:"):
            final_lon = float(line.split(":")[1].strip())
        elif line.startswith("Source_XY:"):
            parts = line.split(":")[1].strip().split(',')
            source_xy_local = (float(parts[0]), float(parts[1]))
        elif line.startswith("Distances_Used:"):
            in_distances_section = True
        elif in_distances_section and line.startswith("-"):
            parts = line.split(":")
            video_name = parts[0].replace('-', '').strip()
            distance = float(parts[1].replace('m', '').strip())
            distances_used.append({"video": video_name, "dist_to_source": distance})
        elif in_distances_section and not line: # End of distances section
            in_distances_section = False

    if final_lat is None or final_lon is None or source_xy_local is None or not distances_used:
        print("Error: Could not parse all required data from stdin.", file=sys.stderr)
        return

    final_lat_dms = to_dms_string(final_lat, True)
    final_lon_dms = to_dms_string(final_lon, False)
    
    report_parts = [
        "# Forensic Audio Analysis: Triangulation of Acoustic Event\n\n",
        "## 1. Objective\nTo determine the geographic origin of a loud \"bang\" event captured on multiple video recording devices.\n\n",
        "## 2. Methodology: Time Difference of Arrival (TDOA)\n",
        "The analysis uses Time Difference of Arrival (TDOA). The core formula is: `Distance = (Time_Sound_Heard - Time_Event_Seen) * Speed_of_Sound`.\n",
        "With distances from multiple known locations, a **Multilateration** algorithm finds the single geographic coordinate that best satisfies all measured distances.\n\n",
        "**Environmental Constants:**\n",
        "- **Speed of Sound:** 349.5 m/s (based on 30°C temperature)\n",
        "- **Subject Location (Origin):** 40.2775277° N, -111.7140278° W\n\n",
        "## 3. Data Analysis and Preparation\n",
        "- **GPS and VTZ data** was sourced from `README.md`.\n",
        "- **Audio Clip Offsets** were parsed from `exec-instructions-*.md` files.\n",
        "- **High-Precision Audio Onsets** for the bang were generated by `onset_analysis.py`.\n\n",
        "## 4. TDOA Calculation and Results\n\n",
        "- **Data Quality Issues:** Some data points were automatically excluded because their source data produced a negative `delta_t` (implying sound arrived before the visual event), indicating an unresolvable error in their provided VTZ or audio offset times. Specifically, `video-1.mp4`, `video-2.MOV`, `video-3.mp4`, `video-7.mp4`, and `video-8.mp4` were skipped.\n\n",
        "The final triangulation was performed using the ", str(len(distances_used)), " valid data points:\n\n",
        "| Video Source | Calculated Distance to Source |\n| :--- | :--- |\n"
    ]
    for d in distances_used:
        report_parts.append(f"| {d['video']} | {d['dist_to_source']:.2f} meters |\n")

    report_parts.append(f"""

A numerical solver minimized the error across these {len(distances_used)} distances.

- **Estimated Location (Local XY): `(x = {source_xy_local[0]:.2f}m, y = {source_xy_local[1]:.2f}m)`**
  *(This is relative to the subject at (0, 0))*

## 5. Final Result: GPS Coordinate of Source

The local XY coordinate was converted back to geographic coordinates.

#### The final estimated GPS coordinate for the source of the bang is:

-   **Latitude:** `{final_lat:.7f}° N`
-   **Longitude:** `{final_lon:.7f}° W`

In Degrees, Minutes, Seconds format:
-   **{final_lat_dms}**
-   **{final_lon_dms}**
"""
    )
    
    with open('shooter-pos.md', 'w') as f:
        f.write("".join(report_parts))
        
    print("Report 'shooter-pos.md' has been generated.", file=sys.stderr)

if __name__ == '__main__':
    generate_report()