https://www.google.com/search?q=explain+crach+thumb+audio+forensic+analysis.+in+reference+to+which+sound+is+the+crack+and+the+thumb&sca_esv=59623aa993e8ccae&sxsrf=ANbL-n4o5ZRE_RlqAwNnve_lBXQ5xZnXnA%3A1768937828911&source=hp&ei=ZNlvacTONeG8seMP_YO90QQ&iflsig=AFdpzrgAAAAAaW_ndEKGti0ZHjeHUubf18-MEnjIKu0-&aep=22&udm=50&ved=0ahUKEwjEkK737pqSAxVhXmwGHf1BL0oQteYPCBk&oq=&gs_lp=Egdnd3Mtd2l6IgBIAFAAWABwAHgAkAEAmAEAoAEAqgEAuAEByAEAmAIAoAIAmAMAkgcAoAcAsgcAuAcAwgcAyAcAgAgB&sclient=gws-wiz&mstk=AUtExfDk_4euHat3ELI69kKnbgYIChyTc5XpkA6_nD6g4eFDZYWY-3fkZMNvSXYPHRQh85wpI0TO6iTy_8oiRKRXZB3udrMIlj5oG6FyhkOey_dHHXI2p41mmjbf1gP-k30gUKLYDx_PadnpCdJnpEOO5_ZAfqv6u4nM7bQAppOjk9StIDuPprvDUavN-h6RhPnt_BudvLdi0JBomqYNSBxILgTW822nYlvwdx_1wA8B5FY1muv3VkpBmpygzG8oJI_701Pnqdv0WeP_2IaO0825tAzo9uOoxTEPiUY&csuir=1&mtid=ktlvadiiJvSq4-EPj5CQ4Qk


In forensic audio analysis, the "crack-thump" (often referred to as crack-pop or crack-boom) is a method used to determine the distance and direction of a shooter based on the sounds produced by a supersonic bullet. 
The two distinct sounds are defined as follows:
The Crack: This is the ballistic shockwave (sonic boom) created by a bullet traveling faster than the speed of sound. For an observer or microphone in the line of fire, this sound arrives first because the projectile itself outpaces the sound of the gun being fired.
The Thump: This is the muzzle blast (the actual "bang") radiating from the firearm's barrel when it is discharged. It travels at the speed of sound and arrives second. 
Forensic Application
Analysts use the time interval between these two sounds to estimate the shooter's distance: 
Distance Estimation: A longer delay between the crack and the thump indicates the shooter is farther away. A rough field estimate is that every second of delay corresponds to approximately 270–300 meters (roughly 300–400 yards).
Origin Location: The timing and intensity of the muzzle blast ("thump") help determine the shooter's direction, whereas the "crack" only indicates that a supersonic projectile passed nearby.
Consistency Check: If multiple shots have a consistent time interval between the crack and thump, it indicates the shooter is at a static position. 


    suppose that in an ampitheater shaped like a triangle with the stage at the base with 16 audio recordings sample from different locations in a 1.900m^2 audio recording catchment area, if the devices where evenly dispersed in the area how many of them would record the "crack" ballistic shockwave


In a scenario with 16 devices evenly dispersed throughout a \(1,900\,\text{m}^{2}\) triangular amphitheater, the number of devices that record the "crack" (ballistic shockwave) depends heavily on the bullet's trajectory relative to the microphones. Key Factors for Recording the "Crack" Shockwave Geometry: Unlike the muzzle blast ("thump"), which radiates in all directions, the "crack" is a conical shockwave that trails behind a supersonic bullet.Detection Zone: A microphone will only record the "crack" if it is positioned within the path of this expanding cone. If the bullet passes far away from a device or is traveling in a direction that points the cone away from it, that device will only record the "thump".Distance and Velocity: The shockwave is heard continuously along the bullet's path as long as it remains supersonic. If the bullet slows below Mach 1 before reaching the end of the amphitheater, devices in the back will not record a crack. Estimated Count Total Dispersion: With 16 devices in \(1,900\,\text{m}^{2}\), each device covers an average area of roughly \(118\,\text{m}^{2}\) (approximately a \(10.9\,\text{m}\times 10.9\,\text{m}\) square).Line of Fire Coverage: Because the shockwave cone is relatively narrow (often between \(20^{\circ }\) and \(60^{\circ }\) depending on bullet speed), only devices near the bullet's trajectory will detect the "crack".Direct Overflight: If the bullet travels through the center of the amphitheater, typically 4 to 6 devices (those closest to the "line of fire") would be in the shockwave's path.Missed Path: If the bullet travels along a perimeter or away from the crowd, it is possible that fewer than 3 or even 0 devices record the crack, while all 16 would likely record the louder, omnidirectional "thump". In forensic practice, at least four spatially distributed microphones are generally required to accurately estimate a trajectory using both crack and thump timings. 



    is there a formula and/or chart that gives/illustrates the increase in radius of the cone's base; and is there a max radius length


In forensic audio analysis, the ballistic shockwave (the crack) is mathematically modeled using the geometry of a Mach Cone. 1. The Mach Angle Formula The radius of the shockwave cone at any given point along the bullet's path is determined by the Mach angle (\(\theta \)), which is the angle between the bullet's trajectory and the shockwave front. The fundamental formula for this angle is:\(\sin (\theta )=\frac{1}{M}\) \(M\): The Mach number (bullet speed divided by the speed of sound).\(\theta \): The Mach angle. 2. Radius of the Cone's Base If you want to find the radius (\(r\)) of the cone at a specific distance (\(d\)) behind the bullet's current position, you use the following relationship:\(r=d\cdot \tan (\theta )\)As the bullet travels farther (increasing \(d\)), the radius of the cone's base increases linearly, creating a wider area of detection for the "crack". Bullet Speed (Mach) Mach Angle (\(\theta \))Radius Expansion Rate (\(r\) per 1m of travel)Mach 1.2 (Subsonic edge)\(\approx 56.4^{\circ }\)\(1.51\,\text{m}\)Mach 2.0 (High velocity)\(30.0^{\circ }\)\(0.58\,\text{m}\)Mach 3.0 (Magnum rifle)\(\approx 19.5^{\circ }\)\(0.35\,\text{m}\)3. Maximum Radius Length There is no "fixed" maximum radius in a purely mathematical sense, but there are physical limits to how far the shockwave travels before it can no longer be recorded as a "crack": Sonic Decay: As the shockwave expands, its energy dissipates. The pressure amplitude drops rapidly with distance (roughly proportional to \(r^{-3/4}\) for an N-wave).Acoustic Horizon: Eventually, the shockwave weakens until it becomes a standard sound wave (low-pressure acoustic wave) or falls below the microphone's noise floor. In typical forensic environments, a detectable "crack" rarely persists beyond 100–200 meters from the bullet's path, even for high-caliber rounds.Velocity Threshold: The shockwave only exists while the bullet is supersonic (\(M>1\)). Once air resistance slows the bullet below the speed of sound, no new shockwaves are generated, and the existing cone "detaches" and dissipates. 